=== 2lambda123/aws-serverless-application-model/samtranslator/validator/sam_schema/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "definitions": {
    "CloudFormationResource": {
      "additionalProperties": true,
      "properties": {
        "Type": {
          "pattern": "^(?!^AWS::Serverless).*",
          "type": "string"
        }
      },
      "required": [
        "Type"
      ],
      "type": "object"
    },
    "Tag": {
      "additionalProperties": false,
      "properties": {
        "Key": {
          "type": "string"
        },
        "Value": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "object"
            }
          ]
        }
      },
      "type": "object"
    }
  },
  "properties": {
    "AWSTemplateFormatVersion": {
      "enum": [
        "2010-09-09"
      ],
      "type": "string"
    },
    "Conditions": {
      "additionalProperties": false,
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "type": "object"
        }
      },
      "type": "object"
    },
    "Description": {
      "description": "Template description",
      "maxLength": 1024,
      "type": "string"
    },
    "Mappings": {
      "additionalProperties": false,
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "type": "object"
        }
      },
      "type": "object"
    },
    "Metadata": {
      "type": "object"
    },
    "Outputs": {
      "additionalProperties": false,
      "maxProperties": 60,
      "minProperties": 1,
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "type": "object"
        }
      },
      "type": "object"
    },
    "Parameters": {
      "type": "object"
    },
    "Resources": {
      "type": "object"
    },
    "Transform": {
      "enum": [
        "AWS::Serverless-2016-10-31"
      ],
      "type": "string"
    },
    "Globals": {
      "type": "object"
    },
    "Properties": {
      "type": "object"
    }
  },
  "required": [
    "Resources"
  ],
  "type": "object"
}

=== 2lambda123/aws-serverless-application-model/tests/translator/output/aws-cn/function_with_custom_conditional_codedeploy_deployment_preference.json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Conditions": {
    "IsDevEnv2": {
      "Fn::Equals": [
        {
          "Ref": "EnvType"
        },
        "prod"
      ]
    },
    "IsDevEnv": {
      "Fn::Equals": [
        {
          "Ref": "EnvType"
        },
        "dev"
      ]
    }
  },
  "Resources": {
    "HelloWorldFunctionRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "ManagedPolicyArns": [
          "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        ],
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              }
            }
          ]
        }
      }
    },
    "HelloWorldFunctionVersion1bc9589ea5": {
      "DeletionPolicy": "Retain",
      "Type": "AWS::Lambda::Version",
      "Properties": {
        "FunctionName": {
          "Ref": "HelloWorldFunction"
        }
      }
    },
    "CodeDeployServiceRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "ManagedPolicyArns": [
          "arn:aws:iam::aws:policy/service-role/AWSCodeDeployRoleForLambda"
        ],
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "codedeploy.amazonaws.com"
                ]
              }
            }
          ]
        }
      }
    },
    "HelloWorldFunctionDeploymentGroup": {
      "Type": "AWS::CodeDeploy::DeploymentGroup",
      "Properties": {
        "ApplicationName": {
          "Ref": "ServerlessDeploymentApplication"
        },
        "AutoRollbackConfiguration": {
          "Enabled": true,
          "Events": [
            "DEPLOYMENT_FAILURE",
            "DEPLOYMENT_STOP_ON_ALARM",
            "DEPLOYMENT_STOP_ON_REQUEST"
          ]
        },
        "ServiceRoleArn": {
          "Fn::GetAtt": [
            "CodeDeployServiceRole",
            "Arn"
          ]
        },
        "DeploymentConfigName": {
          "Fn::If": [
            "IsDevEnv",
            {
              "Fn::If": [
                "IsDevEnv2",
                {
                  "Fn::Sub": [
                    "CodeDeployDefault.Lambda${ConfigName}",
                    {
                      "ConfigName": "AllAtOnce"
                    }
                  ]
                },
                "TestCustomDeploymentConfig"
              ]
            },
            {
              "Fn::Sub": [
                "CodeDeployDefault.Lambda${ConfigName}",
                {
                  "ConfigName": "Canary10Percent15Minutes"
                }
              ]
            }
          ]
        },
        "DeploymentStyle": {
          "DeploymentType": "BLUE_GREEN",
          "DeploymentOption": "WITH_TRAFFIC_CONTROL"
        }
      }
    },
    "ServerlessDeploymentApplication": {
      "Type": "AWS::CodeDeploy::Application",
      "Properties": {
        "ComputePlatform": "Lambda"
      }
    },
    "HelloWorldFunctionAliaslive": {
      "Type": "AWS::Lambda::Alias",
      "UpdatePolicy": {
        "CodeDeployLambdaAliasUpdate": {
          "ApplicationName": {
            "Ref": "ServerlessDeploymentApplication"
          },
          "DeploymentGroupName": {
            "Ref": "HelloWorldFunctionDeploymentGroup"
          }
        }
      },
      "Properties": {
        "FunctionVersion": {
          "Fn::GetAtt": [
            "HelloWorldFunctionVersion1bc9589ea5",
            "Version"
          ]
        },
        "FunctionName": {
          "Ref": "HelloWorldFunction"
        },
        "Name": "live"
      }
    },
    "HelloWorldFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Handler": "index.handler",
        "Code": {
          "S3Bucket": "manvendra-sam-test",
          "S3Key": "b9cfacca4a48ef2097bb36f980cc4481"
        },
        "Role": {
          "Fn::GetAtt": [
            "HelloWorldFunctionRole",
            "Arn"
          ]
        },
        "Runtime": "nodejs8.10",
        "Tags": [
          {
            "Value": "SAM",
            "Key": "lambda:createdBy"
          }
        ]
      }
    }
  },
  "Parameters": {
    "EnvType": {
      "Default": "dev"
    }
  }
}

=== 2lambda123/aws-serverless-application-model/tests/translator/output/aws-us-gov/schema_validation_2.json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "A Step Functions Standard Workflow sending payloads to an SQS queue. This pattern will not wait for a callback from SQS\n",
  "Resources": {
    "MyQueue": {
      "Type": "AWS::SQS::Queue"
    },
    "MyStateMachineExecutionRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  {
                    "Fn::Sub": "states.${AWS::Region}.amazonaws.com"
                  }
                ]
              },
              "Action": "sts:AssumeRole"
            }
          ]
        },
        "Path": "/"
      }
    },
    "StateMachinetoSQS": {
      "Type": "AWS::StepFunctions::StateMachine",
      "Properties": {
        "DefinitionString": {
          "Fn::Join": [
            "\n",
            [
              "{",
              "    \"StartAt\": \"SendToMyQueue\",",
              "    \"States\": {",
              "        \"SendToMyQueue\": {",
              "            \"End\": true,",
              "            \"Parameters\": {",
              "                \"MessageBody.$\": \"$.message\",",
              "                \"QueueUrl\": \"${definition_substitution_1}\"",
              "            },",
              "            \"Resource\": \"aws:aws-us-gov:states:::sqs:sendMessage\",",
              "            \"Type\": \"Task\"",
              "        }",
              "    }",
              "}"
            ]
          ]
        },
        "RoleArn": {
          "Fn::GetAtt": [
            "MyStateMachineExecutionRole",
            "Arn"
          ]
        },
        "Tags": [
          {
            "Key": "stateMachine:createdBy",
            "Value": "SAM"
          }
        ],
        "DefinitionSubstitutions": {
          "definition_substitution_1": {
            "Ref": "MyQueue"
          }
        }
      }
    },
    "SFNToSQSPolicy": {
      "Type": "AWS::IAM::ManagedPolicy",
      "Metadata": {
        "aws:sam:connectors": {
          "SFNToSQS": {
            "Source": {
              "Type": "AWS::Serverless::StateMachine"
            },
            "Destination": {
              "Type": "AWS::SQS::Queue"
            }
          }
        }
      },
      "Properties": {
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "sqs:SendMessage"
              ],
              "Resource": [
                {
                  "Fn::GetAtt": [
                    "MyQueue",
                    "Arn"
                  ]
                }
              ]
            }
          ]
        },
        "Roles": [
          {
            "Ref": "MyStateMachineExecutionRole"
          }
        ]
      }
    }
  },
  "Outputs": {
    "StateMachinetoSQSArn": {
      "Value": {
        "Ref": "StateMachinetoSQS"
      },
      "Description": "StateMachinetoSQS Arn"
    },
    "MyQueueURL": {
      "Value": {
        "Ref": "MyQueue"
      },
      "Description": "MyQueue URL"
    }
  }
}
